version: "3.7"
services:
  db:
    image: postgres:alpine3.16
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - "${POSTGRES_DATA:-./data/postgres/data}:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_DB: "${POSTGRES_DB:-example}"
    restart: always

  backend:
    build: .
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT:-4000}:8000"
    environment:
      PORT: 8000
    depends_on:
      - db
    restart: always